version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: StorageManagerServer
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Trust Server Certificate=true"
      LogService__LogRetentionDays: ${SERVER_LOG_RETENTION_DAYS}
      LogService__LogLevel: ${SERVER_LOG_LEVEL}
    ports:
      - "${API_PORT}:${API_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "${ADDRESS}/health"] 
      interval: 30s
      timeout: 5s
      retries: 3

  client:
    build:
      context: storage-manager-client
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: "${ADDRESS}:${API_PORT}/api"
    depends_on:
      - api
    ports:
      - "3000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "${ADDRESS}:${CLIENT_PORT}"] 
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  db_data:
